name: base
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - _python_abi3_support=1.0
  - anaconda-anon-usage=0.7.5
  - anaconda-auth=0.12.3
  - anaconda-cli-base=0.7.0
  - annotated-types=0.6.0
  - aom=3.12.1
  - archspec=0.2.5
  - asttokens=3.0.1
  - blas=1.0
  - boltons=25.0.0
  - bottleneck=1.4.2
  - brotlicffi=1.2.0.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2026.1.4
  - cairo=1.18.4
  - certifi=2026.01.04
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - click=8.2.1
  - comm=0.2.3
  - conda=25.11.1
  - conda-anaconda-telemetry=0.3.0
  - conda-anaconda-tos=0.2.2
  - conda-content-trust=0.2.0
  - conda-libmamba-solver=25.11.0
  - conda-package-handling=2.4.0
  - conda-package-streaming=0.12.0
  - contourpy=1.3.3
  - cpp-expected=1.1.0
  - cpython=3.13.11
  - cryptography=46.0.3
  - cycler=0.12.1
  - cyrus-sasl=2.1.28
  - dav1d=1.2.1
  - dbus=1.16.2
  - debugpy=1.8.19
  - decorator=5.2.1
  - distro=1.9.0
  - executing=2.2.1
  - expat=2.7.3
  - fmt=11.2.0
  - fontconfig=2.15.0
  - fonttools=4.61.0
  - freetype=2.13.3
  - fribidi=1.0.10
  - frozendict=2.4.6
  - gettext=0.21.0
  - graphite2=1.3.14
  - harfbuzz=10.2.0
  - icu=73.1
  - idna=3.11
  - intel-openmp=2025.0.0
  - ipykernel=7.1.0
  - ipython=9.9.0
  - ipython_pygments_lexers=1.1.1
  - jansson=2.14
  - jaraco.classes=3.4.0
  - jaraco.context=6.0.0
  - jaraco.functools=4.1.0
  - jedi=0.19.2
  - jeepney=0.7.1
  - joblib=1.5.2
  - jpeg=9f
  - jsonpatch=1.33
  - jsonpointer=3.0.0
  - jupyter_client=8.8.0
  - jupyter_core=5.9.1
  - keyring=25.7.0
  - keyutils=1.6.3
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lcms2=2.17
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libarchive=3.8.2
  - libavif=1.3.0
  - libcups=2.4.15
  - libcurl=8.16.0
  - libdeflate=1.22
  - libdrm=2.4.124
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.3
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran-ng=15.2.0
  - libgfortran5=15.2.0
  - libgl=1.7.0
  - libglib=2.84.4
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.2.0
  - libhwloc=2.12.1
  - libiconv=1.16
  - libidn2=2.3.8
  - libkrb5=1.21.3
  - libllvm15=15.0.7
  - libmamba=2.3.2
  - libmambapy=2.3.2
  - libmpdec=4.0.0
  - libnghttp2=1.67.1
  - libopengl=1.7.0
  - libopenjpeg=2.5.4
  - libpciaccess=0.18
  - libpng=1.6.50
  - libpq=17.6
  - libsodium=1.0.20
  - libsolv=0.7.30
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libtiff=4.7.1
  - libunistring=1.3
  - libuuid=1.41.5
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxkbcommon=1.9.1
  - libxml2=2.13.9
  - libzlib=1.3.1
  - lmdb=0.9.31
  - lz4-c=1.9.4
  - markdown-it-py=4.0.0
  - matplotlib=3.10.7
  - matplotlib-base=3.10.7
  - matplotlib-inline=0.2.1
  - mdurl=0.1.2
  - menuinst=2.4.2
  - mesalib=25.1.5
  - mkl=2025.0.0
  - mkl-service=2.5.2
  - mkl_fft=2.1.1
  - mkl_random=1.3.0
  - more-itertools=10.8.0
  - msgpack-python=1.1.1
  - mysql-common=9.3.0
  - mysql-libs=9.3.0
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nlohmann_json=3.11.2
  - numexpr=2.14.1
  - numpy=2.3.5
  - numpy-base=2.3.5
  - openldap=2.6.10
  - openssl=3.6.0
  - packaging=25.0
  - pandas=2.3.3
  - parso=0.8.5
  - pcre2=10.46
  - pexpect=4.9.0
  - pillow=12.0.0
  - pip=25.3
  - pixman=0.46.4
  - pkce=1.0.3
  - platformdirs=4.5.0
  - pluggy=1.5.0
  - prompt-toolkit=3.0.52
  - psutil=7.2.1
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pybind11-abi=5
  - pycosat=0.6.6
  - pycparser=2.23
  - pydantic=2.12.4
  - pydantic-core=2.41.5
  - pydantic-settings=2.12.0
  - pygments=2.19.2
  - pyjwt=2.10.1
  - pyparsing=3.2.5
  - pyqt=6.9.1
  - pyqt6-sip=13.10.2
  - pysocks=1.7.1
  - python=3.13.11
  - python-dateutil=2.9.0post0
  - python-dotenv=1.1.0
  - python-gil=3.13.11
  - python-tzdata=2025.2
  - python_abi=3.13
  - pytz=2025.2
  - pyzmq=27.1.0
  - qtbase=6.9.2
  - qtdeclarative=6.9.2
  - qtsvg=6.9.2
  - qttools=6.9.2
  - qtwayland=6.9.2
  - qtwebchannel=6.9.2
  - qtwebsockets=6.9.2
  - readchar=4.2.1
  - readline=8.3
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - requests=2.32.5
  - rich=14.2.0
  - ruamel.yaml=0.18.16
  - ruamel.yaml.clib=0.2.14
  - scikit-learn=1.8.0
  - scipy=1.16.3
  - secretstorage=3.4.0
  - semver=3.0.4
  - setuptools=80.9.0
  - shellingham=1.5.4
  - simdjson=3.10.1
  - sip=6.12.0
  - six=1.17.0
  - spirv-tools=2025.1
  - sqlite=3.51.0
  - stack_data=0.6.3
  - tbb=2022.3.0
  - tbb-devel=2022.3.0
  - threadpoolctl=3.5.0
  - tk=8.6.15
  - tomli=2.2.1
  - tornado=6.5.4
  - tqdm=4.67.1
  - traitlets=5.14.3
  - truststore=0.10.1
  - typer=0.20.0
  - typer-slim=0.20.0
  - typer-slim-standard=0.20.0
  - typing-extensions=4.15.0
  - typing-inspection=0.4.2
  - typing_extensions=4.15.0
  - tzdata=2025b
  - urllib3=2.6.1
  - wayland=1.24.0
  - wcwidth=0.2.14
  - wheel=0.45.1
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.44
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxshmfence=1.3.3
  - xorg-libxxf86vm=1.1.6
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - yaml-cpp=0.8.0
  - zeromq=4.3.5
  - zlib=1.3.1
  - zstandard=0.24.0
  - zstd=1.5.7
prefix: /home/jgomez/miniconda3
